version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: backend-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: AllCL
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db # phpMyAdmin이 연결할 MySQL의 HOST
      MYSQL_ROOT_PASSWORD: 1234 # MySQL 비밀번호
    ports:
      - 8090:80
    depends_on:
      - db
    restart: always

volumes:
  mysql_data:

# test
