spring:
  application:
    name: Backend-AllCL
  datasource:
    url: jdbc:mysql://localhost:3306/AllCL?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # 콘솔에 SQL 쿼리 표시
        format_sql: true # SQL 쿼리를 보기 쉽게 변환
    database-platform: org.hibernate.dialect.MySQLDialect