spring:
  application:
    name: Backend-AllCL
  datasource:
    url: jdbc:mysql://mysql:3306/AllCL?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
