apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-cd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-cd
  template:
    metadata:
      labels:
        app: order-cd
    spec:
      containers:
        - name: order-cd
          image: 961341508965.dkr.ecr.ap-northeast-2.amazonaws.com/order-ci:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
      imagePullSecrets:
        - name: ecr-registry-secret 
